name: API Control Panel

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action: activate-pinger, or deactivate-pinger"
        required: true
        type: string
      duration_hours:
        description: "How many hours the pinger should be active"
        required: false
        default: "12"
      interval_minutes:
        description: "The ping interval in minutes"
        required: false
        default: "14"

jobs:
  control:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Activate Pinger
        if: ${{ github.event.inputs.action == 'activate-pinger' }}
        run: |
          DURATION="${{ github.event.inputs.duration_hours }} hours"
          INTERVAL="${{ github.event.inputs.interval_minutes }}"
          echo "Activating pinger for $DURATION at a $INTERVAL minute interval..."
          echo "{\"activeUntil\":\"$(date -u -d \"$DURATION\" -Iseconds)\", \"interval\":\"$INTERVAL\"}" > pinger-state.json
          echo "COMMIT_MESSAGE=chore: Activate pinger for ${{ github.event.inputs.duration_hours }} hours" >> $GITHUB_ENV

      - name: Deactivate Pinger
        if: ${{ github.event.inputs.action == 'deactivate-pinger' }}
        run: |
          echo "Deactivating pinger..."
          # Use the last known interval or a default if the file doesn't exist/is malformed
          INTERVAL=$(jq -r .interval pinger-state.json 2>/dev/null || echo "14")
          echo "{\"activeUntil\":\"$(date -u -d '1 second ago' -Iseconds)\", \"interval\":\"$INTERVAL\"}" > pinger-state.json
          echo "COMMIT_MESSAGE=chore: Deactivate pinger" >> $GITHUB_ENV

      - name: Commit and Push State Change
        if: ${{ github.event.inputs.action == 'activate-pinger' || github.event.inputs.action == 'deactivate-pinger' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
          file_pattern: pinger-state.json
