name: Smart Keep-Alive for Render

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check pinger state
        id: check_state
        run: |
          # Read the 'activeUntil' timestamp from the state file
          active_until=$(jq -r .activeUntil pinger-state.json)

          # Get the current time in the same ISO 8601 format
          current_time=$(date -u -Iseconds)

          echo "Pinger active until: $active_until"
          echo "Current time is:     $current_time"

          # Compare the timestamps and set the output variable for the next step
          if [[ "$current_time" < "$active_until" ]]; then
            echo "should_ping=true" >> $GITHUB_OUTPUT
          else
            echo "should_ping=false" >> $GITHUB_OUTPUT
          fi

      - name: Ping the backend URL (if active)
        if: steps.check_state.outputs.should_ping == 'true'
        run: |
          echo "Pinger is active. Pinging Render service..."
          curl -s "https://ankurhalder.onrender.com"
          echo "Ping complete."

      - name: Log inactive state
        if: steps.check_state.outputs.should_ping == 'false'
        run: echo "Pinger is inactive. Skipping ping."
