name: Smart Keep-Alive for Render

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check pinger state
        id: check_state
        run: |
          if [[ ! -f pinger-state.json ]]; then
            echo "State file not found. Assuming pinger is inactive."
            echo "should_ping=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          active_until=$(jq -r .activeUntil pinger-state.json)
          current_time=$(date -u -Iseconds)

          echo "Pinger active until: $active_until"
          echo "Current time is:     $current_time"

          if [[ "$current_time" < "$active_until" ]]; then
            echo "should_ping=true" >> $GITHUB_OUTPUT
          else
            echo "should_ping=false" >> $GITHUB_OUTPUT
          fi

      - name: Ping the backend URL (if active)
        if: steps.check_state.outputs.should_ping == 'true'
        run: |
          echo "Pinger is active. Pinging Render service..."
          curl -sS --fail "https://ankurhalder.onrender.com" || echo "Ping failed."
          echo "Ping complete."

      - name: Log inactive state
        if: steps.check_state.outputs.should_ping == 'false'
        run: echo "Pinger is inactive. Skipping ping."
