name: Smart Keep-Alive for Render

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check pinger state
        id: check_state
        run: |
          active_until=$(jq -r .activeUntil pinger-state.json)
          current_time=$(date -u -Iseconds)

          if [[ "$current_time" < "$active_until" ]]; then
            echo "should_ping=true" >> $GITHUB_OUTPUT
            # We must also re-schedule the workflow dynamically based on the interval
            interval=$(jq -r .interval pinger-state.json)
            echo "Setting new cron interval to */${interval}..."
            sed -i "s/cron: '.\+\_'/cron: '*/${interval} * * * *'/" .github/workflows/keep-alive.yml
            
            # Check if changes were made to the workflow file
            if ! git diff --quiet .github/workflows/keep-alive.yml; then
              git config --global user.name 'GitHub Actions'
              git config --global user.email 'actions@github.com'
              git add .github/workflows/keep-alive.yml
              git commit -m "chore: Adjust pinger interval to ${interval} minutes"
              git push
            fi
          else
            echo "should_ping=false" >> $GITHUB_OUTPUT
          fi

      - name: Ping the backend URL (if active)
        if: steps.check_state.outputs.should_ping == 'true'
        run: |
          echo "Pinger is active. Pinging Render service..."
          curl -s "https://ankurhalder.onrender.com"
          echo "Ping complete."

      - name: Log inactive state
        if: steps.check_state.outputs.should_ping == 'false'
        run: echo "Pinger is inactive. Skipping ping."
